name: Generate Executable

on:
  push:
    branches:
      - master

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          python -m pip install pip wheel setuptools
          pip install -r "src/requirements.txt"
      - name: Build package
        run: pyinstaller -F src/fuelishCLI.py --onefile --clean --name fuelishCLI_WIN
      - name: (Upload) Executable
        id: artifact_upload
        uses: actions/upload-artifact@v3
        with:
          name: fuelishCLI-win
          path: dist
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          python -m pip install pip wheel setuptools
          pip install -r "src/requirements.txt"
      - name: Build package
        run: pyinstaller -F src/fuelishCLI.py --onefile --clean --name fuelishCLI_UNIX
      - name: (Upload) Executable
        id: artifact_upload
        uses: actions/upload-artifact@v3
        with:
          name: fuelishCLI-linux
          path: dist